### ISSUE TITLE
Fix recession relative to frankfort assessment

### ISSUE THREAD

**Issue by crazyGru** [HarmonyAI09/harmony-backend#7]

**Comment by crazyGru** [comment]
Fixed.

**Comment by DitmarHoxha** [comment]
![Image](https://github.com/HarmonyAI09/harmony-backend/assets/157229524/0823305c-81f5-4451-9ade-9fe383be784e)



![Image](https://github.com/HarmonyAI09/harmony-backend/assets/157229524/0c63a22f-2a56-444f-8691-2e5b435a4a93)



![Image](https://github.com/HarmonyAI09/harmony-backend/assets/157229524/b84d901a-f03b-47cc-82b8-ea29b7060279)



![Image](https://github.com/HarmonyAI09/harmony-backend/assets/157229524/3654ba0f-41bf-4e11-bb26-fac75ab0659b)

**Comment by DitmarHoxha** [comment]
![Image](https://github.com/HarmonyAI09/harmony-backend/assets/157229524/eb43fc01-3c99-4129-960e-330d559b6ac2)



![Image](https://github.com/HarmonyAI09/harmony-backend/assets/157229524/37f86aaf-3b47-4d49-8620-3c2031bb3bc8)



![Image](https://github.com/HarmonyAI09/harmony-backend/assets/157229524/ce489cc8-391a-444d-b6cd-2c9c997a9783)



![Image](https://github.com/HarmonyAI09/harmony-backend/assets/157229524/0c56ef0f-9eba-4807-84b9-fbcd7c6be522)
