### ISSUE TITLE
Facial convexity value calculation is wrong when it goes over 180 degrees

### ISSUE THREAD

**Issue by crazyGru** [HarmonyAI09/harmony-backend#8]

**Comment by DitmarHoxha** [comment]
You can see that his facial convexity is concave actually and above 180 degrees. It should be like 186 degrees or something which would be tier 5 or 6, but it says 6 degrees instead.

![Image](https://github.com/HarmonyAI09/harmony-backend/assets/157229524/021a1eb4-b193-4318-9c68-8d47851eaa5a)



![Image](https://github.com/HarmonyAI09/harmony-backend/assets/157229524/408c1888-d7f0-4496-b23b-496068fbd414)

**Comment by crazyGru** [comment]
![Image](https://github.com/HarmonyAI09/harmony-backend/assets/137296569/c527a8d8-2a0c-4fcc-9474-8efd4e4a4305)

Fixed.
