### ISSUE TITLE
BUG: facial thirds scoring seems to be slightly wrong

### ISSUE THREAD

**Issue by crazyGru** [HarmonyAI09/harmony-backend#9]
This should be more like tier 5 based on how high his lower third value is, but it is saying tier 2

![Image](https://github.com/HarmonyAI09/harmony-backend/assets/157229524/ef278a57-3929-48bc-bc3f-b39762eacffe)

![Image](https://github.com/HarmonyAI09/harmony-backend/assets/157229524/18490e7a-44b6-4aff-9999-98e8c795c1cf)

**Comment by DitmarHoxha** [comment]
![Image](https://github.com/HarmonyAI09/harmony-backend/assets/157229524/a0a64253-b700-4395-8e17-a2486bb3074e)

**Comment by crazyGru** [comment]
![Image](https://github.com/HarmonyAI09/harmony-backend/assets/137296569/9b70c657-a690-4150-9950-cc10ea77f83c)

Fixed.
